-- MySQL Script generated by MySQL Workbench
-- 09/04/15 10:43:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Type_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type_User` (
  `idType_User` INT NOT NULL COMMENT '',
  `szDescription` VARCHAR(45) NULL COMMENT '',
  `bActivo` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idType_User`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL COMMENT '',
  `FK_idType_User` INT NOT NULL COMMENT '',
  `szUserName` VARCHAR(45) NULL COMMENT '',
  `szPassword` VARCHAR(45) NOT NULL COMMENT '',
  `bActivo` TINYINT(1) NULL COMMENT '',
  `FirstDate` DATETIME NULL COMMENT '',
  `EndDate` DATETIME NULL COMMENT '',
  PRIMARY KEY (`idUser`, `FK_idType_User`)  COMMENT '',
  INDEX `fk_User_Type_User_idx` (`FK_idType_User` ASC)  COMMENT '',
  CONSTRAINT `fk_User_Type_User`
    FOREIGN KEY (`FK_idType_User`)
    REFERENCES `mydb`.`Type_User` (`idType_User`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nationality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nationality` (
  `idNationality` INT NOT NULL COMMENT '',
  `szNationality` VARCHAR(45) NOT NULL COMMENT '',
  `bactivo` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idNationality`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Info_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Info_User` (
  `idUser_Info` INT NOT NULL COMMENT '',
  `User_idUser` INT NOT NULL COMMENT '',
  `Nationalite_idNationalite` INT NOT NULL COMMENT '',
  `szNameLastName` VARCHAR(100) NOT NULL COMMENT '',
  `szEmail` VARCHAR(45) NULL COMMENT '',
  `szPaisResidente` VARCHAR(45) NULL COMMENT '',
  `Birtheday` DATE NULL COMMENT '',
  PRIMARY KEY (`idUser_Info`, `User_idUser`, `Nationalite_idNationalite`)  COMMENT '',
  INDEX `fk_Info_User_Nationalite1_idx` (`Nationalite_idNationalite` ASC)  COMMENT '',
  CONSTRAINT `fk_Info_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Info_User_Nationalite1`
    FOREIGN KEY (`Nationalite_idNationalite`)
    REFERENCES `mydb`.`Nationality` (`idNationality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Info_Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Info_Place` (
  `idInfo_Place` INT NOT NULL COMMENT '',
  `szDescription` TEXT NOT NULL COMMENT '',
  `Phone` VARCHAR(15) NULL COMMENT '',
  `Address` VARCHAR(200) NULL COMMENT '',
  PRIMARY KEY (`idInfo_Place`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localization` (
  `idlocalization` INT NOT NULL COMMENT '',
  `xlocalitation` INT NOT NULL COMMENT '',
  `ylocalitation` INT NOT NULL COMMENT '',
  `zlocalization` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idlocalization`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Place` (
  `idPlace` INT NOT NULL COMMENT '',
  `idInfo_Place` INT NOT NULL COMMENT '',
  `szReference` VARCHAR(45) NULL COMMENT '',
  `localization_idlocalization` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPlace`, `idInfo_Place`, `localization_idlocalization`)  COMMENT '',
  INDEX `fk_Place_Info_Place1_idx` (`idInfo_Place` ASC)  COMMENT '',
  INDEX `fk_Place_localization1_idx` (`localization_idlocalization` ASC)  COMMENT '',
  CONSTRAINT `fk_Place_Info_Place1`
    FOREIGN KEY (`idInfo_Place`)
    REFERENCES `mydb`.`Info_Place` (`idInfo_Place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Place_localization1`
    FOREIGN KEY (`localization_idlocalization`)
    REFERENCES `mydb`.`localization` (`idlocalization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Language` (
  `idLanguage` INT NOT NULL COMMENT '',
  `szLanguage` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idLanguage`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`content` (
  `idcontent` INT NOT NULL COMMENT '',
  `szpage` VARCHAR(45) NOT NULL COMMENT '',
  `szdescription` TEXT NOT NULL COMMENT '',
  `Language_idLanguage` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcontent`, `Language_idLanguage`)  COMMENT '',
  INDEX `fk_content_Language1_idx` (`Language_idLanguage` ASC)  COMMENT '',
  CONSTRAINT `fk_content_Language1`
    FOREIGN KEY (`Language_idLanguage`)
    REFERENCES `mydb`.`Language` (`idLanguage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `idcomments` INT NOT NULL COMMENT '',
  `szcoment` VARCHAR(500) NOT NULL COMMENT '',
  `Datecreate` DATETIME NULL COMMENT '',
  `User_idUser` INT NOT NULL COMMENT '',
  `Place_idPlace` INT NOT NULL COMMENT '',
  `Place_idInfo_Place` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcomments`, `User_idUser`, `Place_idPlace`, `Place_idInfo_Place`)  COMMENT '',
  INDEX `fk_comments_User1_idx` (`User_idUser` ASC)  COMMENT '',
  INDEX `fk_comments_Place1_idx` (`Place_idPlace` ASC, `Place_idInfo_Place` ASC)  COMMENT '',
  CONSTRAINT `fk_comments_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_Place1`
    FOREIGN KEY (`Place_idPlace` , `Place_idInfo_Place`)
    REFERENCES `mydb`.`Place` (`idPlace` , `idInfo_Place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image_place` (
  `idimage_place` INT NOT NULL COMMENT '',
  `szUrlplace` VARCHAR(250) NULL COMMENT '',
  `Place_idPlace` INT NOT NULL COMMENT '',
  `Place_idInfo_Place` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idimage_place`, `Place_idPlace`, `Place_idInfo_Place`)  COMMENT '',
  INDEX `fk_image_place_Place1_idx` (`Place_idPlace` ASC, `Place_idInfo_Place` ASC)  COMMENT '',
  CONSTRAINT `fk_image_place_Place1`
    FOREIGN KEY (`Place_idPlace` , `Place_idInfo_Place`)
    REFERENCES `mydb`.`Place` (`idPlace` , `idInfo_Place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dictionary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dictionary` (
  `idDictionary` INT NOT NULL COMMENT '',
  `szDescription` VARCHAR(45) NULL COMMENT '',
  `Language_idLanguage` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idDictionary`, `Language_idLanguage`)  COMMENT '',
  INDEX `fk_Dictionary_Language1_idx` (`Language_idLanguage` ASC)  COMMENT '',
  CONSTRAINT `fk_Dictionary_Language1`
    FOREIGN KEY (`Language_idLanguage`)
    REFERENCES `mydb`.`Language` (`idLanguage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catalog` (
  `idCatalog` INT NOT NULL COMMENT '',
  `szDescription` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idCatalog`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `idcountry` INT NOT NULL COMMENT '',
  `szcountry` INT NULL COMMENT '',
  `bactivo` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`idcountry`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
